<a href="https://colab.research.google.com/github/prasad2154/NewVision/blob/main/Day17_DS_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**

In [7]:
import numpy as np

In [8]:
# mostly use in array----
#  Background data structure is array--
# array is sequential data of blcoks
# support indexing slicing


In [9]:
# 1-D array
a= np.array([20,10,99,20,100,233])
a

array([ 20,  10,  99,  20, 100, 233])

In [10]:
np

<module 'numpy' from '/usr/local/lib/python3.12/dist-packages/numpy/__init__.py'>

In [11]:
np.__version__   # to check version

'2.0.2'

In [12]:
# features----------------------->>>
# Powerful n dimentionall array
# numerical computing tool
# open source
# interoperable
# performant
# easy to use

In [13]:
a

array([ 20,  10,  99,  20, 100, 233])

In [14]:
a.sort()
a

array([ 10,  20,  20,  99, 100, 233])

In [15]:
# Find max number
a.max()

np.int64(233)

In [16]:
a.min()

np.int64(10)

In [17]:
# How many present elements
a.size  #to check count

6

In [18]:
# dimension
a.ndim

1

In [19]:
type(a)

numpy.ndarray

In [20]:
# Q what is type of Numpy array  ? ---ndarray

In [21]:
b = np.array([[10,20,1],
              [-1,5,9],
              [7,40,2]])
b

array([[10, 20,  1],
       [-1,  5,  9],
       [ 7, 40,  2]])

In [22]:
b.ndim

2

In [23]:
#  to check number of rows and columns
b.shape  # (rows,column)

(3, 3)

In [24]:
# addition of all elements
print(b.sum())

93


In [25]:
b

array([[10, 20,  1],
       [-1,  5,  9],
       [ 7, 40,  2]])

In [26]:
# columnwise addition

print(b.sum(axis=0))

[16 65 12]


In [27]:
print(b.sum(axis=1))

[31 13 49]


In [28]:
#  Assignment   b.min (),b.max(),b.mean(),b.std()




**Assignment**

In [61]:
b.min()   #Returns the smallest value in the array.

np.int64(-1)

In [67]:
print(b.max())  #Returns the largest value in the array.


40


In [66]:
print(b.mean())

# Returns the average (mean) of all values.

10.333333333333334


In [65]:
 print(b.std())

# Returns the standard deviation, which measures how spread out the values are from the mean.

12.01850425154663


In [68]:
# all in one example
import numpy as np

b = np.array([56,98,125,3654,987,425,125,42,552,800])

print("Minimum:", b.min())
print("Maximum:", b.max())
print("Mean:", b.mean())
print("Standard Deviation:", b.std())

Minimum: 42
Maximum: 3654
Mean: 686.4
Standard Deviation: 1038.5335045149002


## Different ways to creating numpy arrays

In [30]:
# numpy array with random numbers

np.random.random(5)

array([0.9532772 , 0.07120557, 0.44328803, 0.46923258, 0.96779874])

In [33]:
np.random.random((5,5))

array([[0.69109789, 0.25554998, 0.4882829 , 0.44768929, 0.15384234],
       [0.49419102, 0.80426169, 0.77502546, 0.76298488, 0.37037087],
       [0.24341378, 0.48054113, 0.49522899, 0.49512008, 0.18759877],
       [0.20875262, 0.47600519, 0.22071897, 0.23585018, 0.05157578],
       [0.3530584 , 0.26910287, 0.26929082, 0.62861013, 0.72108711]])

In [31]:
# 3D Array (block,rows,column)

In [32]:
np.random.random((3,3,3))

array([[[0.01240058, 0.9604593 , 0.57132279],
        [0.30272521, 0.55573635, 0.85172638],
        [0.4971024 , 0.30182773, 0.88824485]],

       [[0.23095334, 0.0814081 , 0.10290724],
        [0.06003913, 0.46131076, 0.6376926 ],
        [0.46933277, 0.09640529, 0.63231422]],

       [[0.08993973, 0.22337508, 0.69325273],
        [0.14710061, 0.45037867, 0.23751218],
        [0.9717593 , 0.48225937, 0.9005851 ]]])

In [37]:
# generate array with sequence of numbers
c=np.arange(24)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [38]:
c.size

24

In [51]:
# convert from 1D TO 2D
# use reshape--which is temporary
c.reshape(6,4)
# c.reshape(8,3)
# c.reshape(12,2)
# c.reshape(4,6)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [55]:
# resize()---use for permanant changes in dimension

c.resize(6,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [57]:
c.shape

(6, 4)

In [58]:
# convert nD to 1D---USE ravel()-----r=temporary
c.ravel()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])