<a href="https://colab.research.google.com/github/prasad2154/NewVision/blob/main/Day17_DS_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**

In [ ]:
import numpy as np

In [ ]:
# mostly use in array----
#  Background data structure is array--
# array is sequential data of blcoks
# support indexing slicing


In [ ]:
# 1-D array
a= np.array([20,10,99,20,100,233])
a

array([ 20,  10,  99,  20, 100, 233])

In [ ]:
np

<module 'numpy' from '/usr/local/lib/python3.12/dist-packages/numpy/__init__.py'>

In [ ]:
np.__version__   # to check version

'2.0.2'

In [ ]:
# features----------------------->>>
# Powerful n dimentionall array
# numerical computing tool
# open source
# interoperable
# performant
# easy to use

In [ ]:
a

array([ 20,  10,  99,  20, 100, 233])

In [ ]:
a.sort()
a

array([ 10,  20,  20,  99, 100, 233])

In [ ]:
# Find max number
a.max()

np.int64(233)

In [ ]:
a.min()

np.int64(10)

In [ ]:
# How many present elements
a.size  #to check count

6

In [ ]:
# dimension
a.ndim

1

In [ ]:
type(a)

numpy.ndarray

In [ ]:
# Q what is type of Numpy array  ? ---ndarray

In [ ]:
b = np.array([[10,20,1],
              [-1,5,9],
              [7,40,2]])
b

array([[10, 20,  1],
       [-1,  5,  9],
       [ 7, 40,  2]])

In [ ]:
b.ndim

2

In [ ]:
#  to check number of rows and columns
b.shape  # (rows,column)

(3, 3)

In [ ]:
# addition of all elements
print(b.sum())

93


In [ ]:
b

array([[10, 20,  1],
       [-1,  5,  9],
       [ 7, 40,  2]])

In [ ]:
# columnwise addition

print(b.sum(axis=0))

[16 65 12]


In [ ]:
print(b.sum(axis=1))

[31 13 49]


In [ ]:
#  Assignment   b.min (),b.max(),b.mean(),b.std()




**Assignment**

In [ ]:
b.min()   #Returns the smallest value in the array.

np.int64(-1)

In [ ]:
print(b.max())  #Returns the largest value in the array.


40


In [ ]:
print(b.mean())

# Returns the average (mean) of all values.

10.333333333333334


In [ ]:
 print(b.std())

# Returns the standard deviation, which measures how spread out the values are from the mean.

12.01850425154663


In [ ]:
# all in one example
import numpy as np

b = np.array([56,98,125,3654,987,425,125,42,552,800])

print("Minimum:", b.min())
print("Maximum:", b.max())
print("Mean:", b.mean())
print("Standard Deviation:", b.std())

Minimum: 42
Maximum: 3654
Mean: 686.4
Standard Deviation: 1038.5335045149002


## Different ways to creating numpy arrays

In [ ]:
# numpy array with random numbers

np.random.random(5)

array([0.08990256, 0.52333823, 0.5932862 , 0.96503774, 0.78161906])

In [ ]:
np.random.random((5,5))

array([[0.16500034, 0.66873647, 0.31197943, 0.71055345, 0.47684669],
       [0.05640242, 0.18908153, 0.20101502, 0.34020893, 0.78558891],
       [0.91023145, 0.84360635, 0.4372924 , 0.74776438, 0.96585702],
       [0.20445273, 0.87094519, 0.61774539, 0.04186031, 0.69410293],
       [0.02378712, 0.04236788, 0.3963796 , 0.6270822 , 0.29245391]])

In [ ]:
# 3D Array (block,rows,column)

In [ ]:
np.random.random((3,3,3))

array([[[0.81756802, 0.59840122, 0.16413397],
        [0.78821982, 0.92601961, 0.90709364],
        [0.0838811 , 0.6317321 , 0.69130433]],

       [[0.19570198, 0.83597324, 0.89641818],
        [0.37066751, 0.53059192, 0.13735893],
        [0.59418079, 0.89561   , 0.586212  ]],

       [[0.30470224, 0.93856586, 0.61682342],
        [0.12972426, 0.103877  , 0.56935768],
        [0.6975025 , 0.65538588, 0.32717054]]])

In [ ]:
# generate array with sequence of numbers
c=np.arange(24)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
c.size

24

In [ ]:
# convert from 1D TO 2D
# use reshape--which is temporary
c.reshape(6,4)
# c.reshape(8,3)
# c.reshape(12,2)
# c.reshape(4,6)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# resize()---use for permanant changes in dimension

c.resize(6,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
c.shape

(6, 4)

In [ ]:
# convert nD to 1D---USE ravel()-----r=temporary
c.ravel()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## **Numpy** **Operation**

In [ ]:
# Such type of question will asked in interview..

In [ ]:

# Create an array of4*4 zeros
import numpy as np

np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.full(( 4,4),0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
# conversion of data type from one to other
# create an array with constant value
np.full(( 4,4),0 ,dtype=bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
np.full(( 5,5),5 ,dtype=complex)

array([[5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j],
       [5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j],
       [5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j],
       [5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j],
       [5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j]])

In [ ]:
# Q2, crete a numpy array 4 * 4 with diagonal elements as true and non-digonal elemen false
np.identity(5 , dtype=bool)  # sqaure matrix 2D  "[[]]""

# in python except zero, None everything is TRUE

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [ ]:
# Q2, crete a numpy array 4 * 4 with diagonal elements as false and non-digonal elemen true
#  we need negation so use ~ before expression
~np.identity(5 , dtype=bool)

array([[False,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True,  True, False]])

In [ ]:
# access diagonal elements of numpy array
s=np.identity(5 , dtype=bool)
s.diagonal()


array([ True,  True,  True,  True,  True])

## **Numpy Slicing and Indexing**

In [ ]:
x= np.arange(24).reshape((6,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
x[0]

array([0, 1, 2, 3])

In [ ]:
x[4]

array([16, 17, 18, 19])

In [ ]:
x[::-1]

array([[20, 21, 22, 23],
       [16, 17, 18, 19],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [ ]:
x[2]

array([ 8,  9, 10, 11])

In [ ]:
print(x[2][3])   # row with element index

11


In [ ]:
print(x[5][3])

23


In [ ]:
print(x[3][2])

14


In [ ]:
# numpy array is mutable in nature
x[3,3]

np.int64(15)

In [ ]:
# replace 15 by 50
x[3,3]=50
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 50],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
x[4,2]=70
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 50],
       [16, 17, 70, 19],
       [20, 21, 22, 23]])

In [ ]:
# access more rows
x[:] #[start_index,stop_index]
x[1:4]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 50]])

In [ ]:
x[3:]

array([[12, 13, 14, 50],
       [16, 17, 70, 19],
       [20, 21, 22, 23]])

In [ ]:
x[-3:]

array([[12, 13, 14, 50],
       [16, 17, 70, 19],
       [20, 21, 22, 23]])

In [ ]:
# column operations
x[:,:]  #[row,column]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 50],
       [16, 17, 70, 19],
       [20, 21, 22, 23]])

In [ ]:
x[-2:]

array([[16, 17, 70, 19],
       [20, 21, 22, 23]])

In [ ]:
x[-2:,-2:]

array([[70, 19],
       [22, 23]])

In [ ]:
x[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
x[1:3,-2:]

array([[ 6,  7],
       [10, 11]])

In [ ]:
# [8,11][12 50]
x[2:4,::3]

array([[ 8, 11],
       [12, 50]])

**Practice**

In [ ]:
p= np.arange(40).reshape((8,5))
p

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [ ]:
p[::-1]

array([[35, 36, 37, 38, 39],
       [30, 31, 32, 33, 34],
       [25, 26, 27, 28, 29],
       [20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [ ]:
p[2:5]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
p[2:5,:2]

array([[10, 11],
       [15, 16],
       [20, 21]])

In [ ]:
p[2:5,1:]

array([[11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [ ]:
p[3:6]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
p[3:6,3:]

array([[18, 19],
       [23, 24],
       [28, 29]])