<a href="https://colab.research.google.com/github/prasad2154/NewVision/blob/main/Day17_DS_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**

In [18]:
import numpy as np

In [19]:
# mostly use in array----
#  Background data structure is array--
# array is sequential data of blcoks
# support indexing slicing


In [20]:
# 1-D array
a= np.array([20,10,99,20,100,233])
a

array([ 20,  10,  99,  20, 100, 233])

In [21]:
np

<module 'numpy' from '/usr/local/lib/python3.12/dist-packages/numpy/__init__.py'>

In [22]:
np.__version__   # to check version

'2.0.2'

In [23]:
# features----------------------->>>
# Powerful n dimentionall array
# numerical computing tool
# open source
# interoperable
# performant
# easy to use

In [24]:
a

array([ 20,  10,  99,  20, 100, 233])

In [25]:
a.sort()
a

array([ 10,  20,  20,  99, 100, 233])

In [26]:
# Find max number
a.max()

np.int64(233)

In [27]:
a.min()

np.int64(10)

In [28]:
# How many present elements
a.size  #to check count

6

In [29]:
# dimension
a.ndim

1

In [30]:
type(a)

numpy.ndarray

In [31]:
# Q what is type of Numpy array  ? ---ndarray

In [32]:
b = np.array([[10,20,1],
              [-1,5,9],
              [7,40,2]])
b

array([[10, 20,  1],
       [-1,  5,  9],
       [ 7, 40,  2]])

In [33]:
b.ndim

2

In [34]:
#  to check number of rows and columns
b.shape  # (rows,column)

(3, 3)

In [35]:
# addition of all elements
print(b.sum())

93


In [36]:
b

array([[10, 20,  1],
       [-1,  5,  9],
       [ 7, 40,  2]])

In [37]:
# columnwise addition

print(b.sum(axis=0))

[16 65 12]


In [38]:
print(b.sum(axis=1))

[31 13 49]


In [39]:
#  Assignment   b.min (),b.max(),b.mean(),b.std()




**Assignment**

In [40]:
b.min()   #Returns the smallest value in the array.

np.int64(-1)

In [41]:
print(b.max())  #Returns the largest value in the array.


40


In [42]:
print(b.mean())

# Returns the average (mean) of all values.

10.333333333333334


In [43]:
 print(b.std())

# Returns the standard deviation, which measures how spread out the values are from the mean.

12.01850425154663


In [44]:
# all in one example
import numpy as np

b = np.array([56,98,125,3654,987,425,125,42,552,800])

print("Minimum:", b.min())
print("Maximum:", b.max())
print("Mean:", b.mean())
print("Standard Deviation:", b.std())

Minimum: 42
Maximum: 3654
Mean: 686.4
Standard Deviation: 1038.5335045149002


## Different ways to creating numpy arrays

In [45]:
# numpy array with random numbers

np.random.random(5)

array([0.4487678 , 0.03032877, 0.91528046, 0.41095961, 0.65061864])

In [46]:
np.random.random((5,5))

array([[0.80340876, 0.92009384, 0.80980388, 0.3231812 , 0.62689337],
       [0.18345334, 0.9969203 , 0.75622711, 0.04382512, 0.74507468],
       [0.59777816, 0.76612821, 0.83398322, 0.14111816, 0.87276435],
       [0.94906063, 0.24919786, 0.69811227, 0.30265845, 0.72960933],
       [0.17254198, 0.85660229, 0.9984421 , 0.14354647, 0.33964844]])

In [47]:
# 3D Array (block,rows,column)

In [48]:
np.random.random((3,3,3))

array([[[0.45564113, 0.33771166, 0.6434377 ],
        [0.57853343, 0.39926145, 0.82984161],
        [0.64739762, 0.21380398, 0.77528767]],

       [[0.57962454, 0.48174638, 0.65808405],
        [0.37196675, 0.68242354, 0.19069245],
        [0.20236106, 0.00871176, 0.69454725]],

       [[0.69947033, 0.85496492, 0.24762268],
        [0.88021967, 0.99938949, 0.25373265],
        [0.39944879, 0.26720322, 0.38770646]]])

In [49]:
# generate array with sequence of numbers
c=np.arange(24)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [50]:
c.size

24

In [51]:
# convert from 1D TO 2D
# use reshape--which is temporary
c.reshape(6,4)
# c.reshape(8,3)
# c.reshape(12,2)
# c.reshape(4,6)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [52]:
# resize()---use for permanant changes in dimension

c.resize(6,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [53]:
c.shape

(6, 4)

In [54]:
# convert nD to 1D---USE ravel()-----r=temporary
c.ravel()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## **Numpy** **Operation**

In [55]:
# Such type of question will asked in interview..

In [56]:

# Create an array of4*4 zeros
import numpy as np

np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [57]:
np.full(( 4,4),0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [58]:
# conversion of data type from one to other
# create an array with constant value
np.full(( 4,4),0 ,dtype=bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [59]:
np.full(( 5,5),5 ,dtype=complex)

array([[5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j],
       [5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j],
       [5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j],
       [5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j],
       [5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j]])

In [60]:
# Q2, crete a numpy array 4 * 4 with diagonal elements as true and non-digonal elemen false
np.identity(5 , dtype=bool)  # sqaure matrix 2D  "[[]]""

# in python except zero, None everything is TRUE

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [61]:
# Q2, crete a numpy array 4 * 4 with diagonal elements as false and non-digonal elemen true
#  we need negation so use ~ before expression
~np.identity(5 , dtype=bool)

array([[False,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True,  True, False]])

In [62]:
# access diagonal elements of numpy array
s=np.identity(5)
s.diagonal()


array([1., 1., 1., 1., 1.])

## **Numpy Slicing and Indexing**

In [64]:
x= np.arange(24).reshape((6,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [65]:
x[0]

array([0, 1, 2, 3])

In [66]:
x[4]

array([16, 17, 18, 19])

In [67]:
x[::-1]

array([[20, 21, 22, 23],
       [16, 17, 18, 19],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [71]:
x[2]

array([ 8,  9, 10, 11])

In [73]:
print(x[2][3])   # row with element index

11


In [74]:
print(x[5][3])

23


In [77]:
print(x[3][2])

14


In [79]:
# numpy array is mutable in nature
x[3,3]

np.int64(15)

In [80]:
# replace 15 by 50
x[3,3]=50
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 50],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [81]:
x[4,2]=70
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 50],
       [16, 17, 70, 19],
       [20, 21, 22, 23]])

In [82]:
# access more rows
x[:] #[start_index,stop_index]
x[1:4]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 50]])

In [84]:
x[3:]

array([[12, 13, 14, 50],
       [16, 17, 70, 19],
       [20, 21, 22, 23]])

In [87]:
x[-3:]

array([[12, 13, 14, 50],
       [16, 17, 70, 19],
       [20, 21, 22, 23]])

In [88]:
# column operations
x[:,:]  #[row,column]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 50],
       [16, 17, 70, 19],
       [20, 21, 22, 23]])

In [91]:
x[-2:]

array([[16, 17, 70, 19],
       [20, 21, 22, 23]])

In [94]:
x[-2:,-2:]

array([[70, 19],
       [22, 23]])

In [96]:
x[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [100]:
x[1:3,-2:]

array([[ 6,  7],
       [10, 11]])

In [101]:
# [8,11][12 50]
x[2:4,::3]

array([[ 8, 11],
       [12, 50]])