<a href="https://colab.research.google.com/github/prasad2154/NewVision/blob/main/Day17_DS_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**

In [22]:
import numpy as np

In [23]:
# mostly use in array----
#  Background data structure is array--
# array is sequential data of blcoks
# support indexing slicing


In [24]:
# 1-D array
a= np.array([20,10,99,20,100,233])
a

array([ 20,  10,  99,  20, 100, 233])

In [25]:
np

<module 'numpy' from '/usr/local/lib/python3.12/dist-packages/numpy/__init__.py'>

In [26]:
np.__version__   # to check version

'2.0.2'

In [27]:
# features----------------------->>>
# Powerful n dimentionall array
# numerical computing tool
# open source
# interoperable
# performant
# easy to use

In [28]:
a

array([ 20,  10,  99,  20, 100, 233])

In [29]:
a.sort()
a

array([ 10,  20,  20,  99, 100, 233])

In [30]:
# Find max number
a.max()

np.int64(233)

In [31]:
a.min()

np.int64(10)

In [32]:
# How many present elements
a.size  #to check count

6

In [33]:
# dimension
a.ndim

1

In [34]:
type(a)

numpy.ndarray

In [35]:
# Q what is type of Numpy array  ? ---ndarray

In [36]:
b = np.array([[10,20,1],
              [-1,5,9],
              [7,40,2]])
b

array([[10, 20,  1],
       [-1,  5,  9],
       [ 7, 40,  2]])

In [37]:
b.ndim

2

In [38]:
#  to check number of rows and columns
b.shape  # (rows,column)

(3, 3)

In [39]:
# addition of all elements
print(b.sum())

93


In [40]:
b

array([[10, 20,  1],
       [-1,  5,  9],
       [ 7, 40,  2]])

In [41]:
# columnwise addition

print(b.sum(axis=0))

[16 65 12]


In [42]:
print(b.sum(axis=1))

[31 13 49]


In [43]:
#  Assignment   b.min (),b.max(),b.mean(),b.std()




**Assignment**

In [44]:
b.min()   #Returns the smallest value in the array.

np.int64(-1)

In [45]:
print(b.max())  #Returns the largest value in the array.


40


In [46]:
print(b.mean())

# Returns the average (mean) of all values.

10.333333333333334


In [47]:
 print(b.std())

# Returns the standard deviation, which measures how spread out the values are from the mean.

12.01850425154663


In [48]:
# all in one example
import numpy as np

b = np.array([56,98,125,3654,987,425,125,42,552,800])

print("Minimum:", b.min())
print("Maximum:", b.max())
print("Mean:", b.mean())
print("Standard Deviation:", b.std())

Minimum: 42
Maximum: 3654
Mean: 686.4
Standard Deviation: 1038.5335045149002


## Different ways to creating numpy arrays

In [49]:
# numpy array with random numbers

np.random.random(5)

array([0.84082363, 0.62321246, 0.079766  , 0.22629308, 0.05602432])

In [50]:
np.random.random((5,5))

array([[0.86053546, 0.67268388, 0.83293135, 0.52150159, 0.82307179],
       [0.97633866, 0.82183721, 0.36977243, 0.60418026, 0.82735881],
       [0.36231076, 0.10727464, 0.55262679, 0.05608348, 0.31981792],
       [0.67114384, 0.9187263 , 0.11241441, 0.6660509 , 0.76296778],
       [0.80397079, 0.52243411, 0.37505932, 0.31439292, 0.87670356]])

In [51]:
# 3D Array (block,rows,column)

In [52]:
np.random.random((3,3,3))

array([[[0.59927264, 0.2167478 , 0.11813475],
        [0.18885512, 0.15115171, 0.62165094],
        [0.81445827, 0.42201862, 0.95900646]],

       [[0.05526241, 0.67847868, 0.07727075],
        [0.21236644, 0.98298463, 0.31079115],
        [0.16945887, 0.27105238, 0.28593234]],

       [[0.54388947, 0.92823195, 0.89456442],
        [0.8098917 , 0.91287788, 0.18112437],
        [0.93956822, 0.70858634, 0.62501466]]])

In [53]:
# generate array with sequence of numbers
c=np.arange(24)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [54]:
c.size

24

In [55]:
# convert from 1D TO 2D
# use reshape--which is temporary
c.reshape(6,4)
# c.reshape(8,3)
# c.reshape(12,2)
# c.reshape(4,6)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [56]:
# resize()---use for permanant changes in dimension

c.resize(6,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [57]:
c.shape

(6, 4)

In [58]:
# convert nD to 1D---USE ravel()-----r=temporary
c.ravel()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## **Numpy** **Operation**

In [59]:
# Such type of question will asked in interview..

In [60]:

# Create an array of4*4 zeros
import numpy as np

np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [61]:
np.full(( 4,4),0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [62]:
# conversion of data type from one to other
# create an array with constant value
np.full(( 4,4),0 ,dtype=bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [63]:
np.full(( 5,5),5 ,dtype=complex)

array([[5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j],
       [5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j],
       [5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j],
       [5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j],
       [5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j, 5.+0.j]])

In [64]:
# Q2, crete a numpy array 4 * 4 with diagonal elements as true and non-digonal elemen false
np.identity(5 , dtype=bool)  # sqaure matrix 2D  "[[]]""

# in python except zero, None everything is TRUE

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [65]:
# Q2, crete a numpy array 4 * 4 with diagonal elements as false and non-digonal elemen true
#  we need negation so use ~ before expression
~np.identity(5 , dtype=bool)

array([[False,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True,  True, False]])

In [66]:
# access diagonal elements of numpy array
s=np.identity(5 , dtype=bool)
s.diagonal()


array([ True,  True,  True,  True,  True])

## **Numpy Slicing and Indexing**

In [67]:
x= np.arange(24).reshape((6,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [68]:
x[0]

array([0, 1, 2, 3])

In [69]:
x[4]

array([16, 17, 18, 19])

In [70]:
x[::-1]

array([[20, 21, 22, 23],
       [16, 17, 18, 19],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [71]:
x[2]

array([ 8,  9, 10, 11])

In [72]:
print(x[2][3])   # row with element index

11


In [73]:
print(x[5][3])

23


In [74]:
print(x[3][2])

14


In [75]:
# numpy array is mutable in nature
x[3,3]

np.int64(15)

In [76]:
# replace 15 by 50
x[3,3]=50
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 50],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [77]:
x[4,2]=70
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 50],
       [16, 17, 70, 19],
       [20, 21, 22, 23]])

In [78]:
# access more rows
x[:] #[start_index,stop_index]
x[1:4]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 50]])

In [79]:
x[3:]

array([[12, 13, 14, 50],
       [16, 17, 70, 19],
       [20, 21, 22, 23]])

In [80]:
x[-3:]

array([[12, 13, 14, 50],
       [16, 17, 70, 19],
       [20, 21, 22, 23]])

In [81]:
# column operations
x[:,:]  #[row,column]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 50],
       [16, 17, 70, 19],
       [20, 21, 22, 23]])

In [82]:
x[-2:]

array([[16, 17, 70, 19],
       [20, 21, 22, 23]])

In [83]:
x[-2:,-2:]

array([[70, 19],
       [22, 23]])

In [84]:
x[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [85]:
x[1:3,-2:]

array([[ 6,  7],
       [10, 11]])

In [86]:
# [8,11][12 50]
x[2:4,::3]

array([[ 8, 11],
       [12, 50]])

**Practice**

In [87]:
p= np.arange(40).reshape((8,5))
p

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [88]:
p[::-1]

array([[35, 36, 37, 38, 39],
       [30, 31, 32, 33, 34],
       [25, 26, 27, 28, 29],
       [20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [89]:
p[2:5]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [90]:
p[2:5,:2]

array([[10, 11],
       [15, 16],
       [20, 21]])

In [91]:
p[2:5,1:]

array([[11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [92]:
p[3:6]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [93]:
p[3:6,3:]

array([[18, 19],
       [23, 24],
       [28, 29]])