<a href="https://colab.research.google.com/github/prasad2154/NewVision/blob/main/Day17_DS_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**

In [1]:
import numpy as np

In [ ]:
# mostly use in array----
#  Background data structure is array--
# array is sequential data of blcoks
# support indexing slicing


In [2]:
# 1-D array
a= np.array([20,10,99,20,100,233])
a

array([ 20,  10,  99,  20, 100, 233])

In [3]:
np

<module 'numpy' from '/usr/local/lib/python3.12/dist-packages/numpy/__init__.py'>

In [9]:
np.__version__   # to check version

'2.0.2'

In [ ]:
# features----------------------->>>
# Powerful n dimentionall array
# numerical computing tool
# open source
# interoperable
# performant
# easy to use

In [5]:
a

array([ 20,  10,  99,  20, 100, 233])

In [7]:
a.sort()
a

array([ 10,  20,  20,  99, 100, 233])

In [10]:
# Find max number
a.max()

np.int64(233)

In [11]:
a.min()

np.int64(10)

In [13]:
# How many present elements
a.size  #to check count

6

In [14]:
# dimension
a.ndim

1

In [15]:
type(a)

numpy.ndarray

In [ ]:
# Q what is type of Numpy array  ? ---ndarray

In [16]:
b = np.array([[10,20,1],
              [-1,5,9],
              [7,40,2]])
b

array([[10, 20,  1],
       [-1,  5,  9],
       [ 7, 40,  2]])

In [17]:
b.ndim

2

In [19]:
#  to check number of rows and columns
b.shape  # (rows,column)

(3, 3)

In [21]:
# addition of all elements
print(b.sum())

93


In [22]:
b

array([[10, 20,  1],
       [-1,  5,  9],
       [ 7, 40,  2]])

In [23]:
# columnwise addition

print(b.sum(axis=0))

[16 65 12]


In [25]:
print(b.sum(axis=1))

[31 13 49]


In [ ]:
#  Assignment   b.min (),b.max(),b.mean(),b.std()


In [ ]:
n

## Different ways to creating numpy arrays